stages:
- name: Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sinourain/mr_sys:latest
      pushRemote: true
      registry: 025872836752.dkr.ecr.us-east-1.amazonaws.com
    when:
      branch:
        include:
        - master
      event:
        include:
        - push
        - pull_request
- name: Build Movie Reservation System
  steps:
  - runScriptConfig:
      image: sinourain/mr_sys:latest
      shellScript: |-
        gem install bundler
        bundle check || bundle install
        RACK_ENV=test bundle exec rake db:migrate
        bundle exec rspec spec
    env:
      POSTGRES_DB: mr_sys
      POSTGRES_HOST: 10.43.1.87
      POSTGRES_PASSWORD: admin123
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgresadmin
      RACK_ENV: development
    when:
      branch:
        include:
        - master
      event:
        include:
        - push
        - pull_request
notification: {}
