version: '3'

services:
  web:
    build:
      context: .
    command: >
      bash -c "gem install bundler
      && bundle check || bundle install
      && bundle exec rake db:migrate
      && bundle exec rackup -p 3000"  
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - gems:/box
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  bundle:
    image: busybox
    volumes:
      - gems:/box

volumes:
  gems:
  pgdata: